/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Models.User;
import java.awt.Toolkit;

/**
 *
 * @author sangtm
 */
public class Main extends javax.swing.JFrame {

    QLDanhMuc qldanhmuc;
    QLMonAn qlmonan;
    QLBanHang qlbanhang;
    QLHoaDon qlhoadon;
    ThongKe thongke;
    QLKhachHang qlkhachhang;
    QLNhanVien qlnhanvien;
    static DoiMatKhau doimatkhau;

    static User user;

    /**
     * Creates new form Main
     */
    public Main(User u) {
        this.user = u;
        initComponents();
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(Main.class.getResource("/Img/homepage.png")));
        System.out.println(u.toString());
        if (!u.getRole().equals("admin")) {
            mnit_thongke.setEnabled(false);
            mnit_qlnhanvien.setEnabled(false);
        } else {
            mnit_taohoadon.setEnabled(false);
        }
    }

    public static void changePassMain(String pass) {
        user.setPassword(pass);
        System.out.println(user.toString());
    }

    public void updateMain() {
        if (qldanhmuc != null) {
            qldanhmuc.loadList();
            qldanhmuc.fillTable();
            qldanhmuc.clearForm();
            qldanhmuc.selectFirstRow();
        }
        if (qlmonan != null) {
            qlmonan.loadList();
            qlmonan.addItemDanhMuc();
            qlmonan.fillTable();
            qlmonan.clearForm();
            qlmonan.selectFirstRow();
        }
        if (qlbanhang != null) {
            qlbanhang.loadList();
            qlbanhang.addItemMonAn();
            qlbanhang.clearForm();
        }
        if (qlhoadon != null) {
            qlhoadon.loadListHD();
            qlhoadon.fillTable();
            qlhoadon.clearTableHDCT();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnit_qldanhmuc = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnit_qlmonan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnit_taohoadon = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnit_qlhoadon = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnit_thongke = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnit_qlkhachhang = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnit_qlnhanvien = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnit_doimatkhau = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý quán ăn Ayza");
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 153));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jMenuBar1.setBorder(null);

        jMenu1.setText("Menu");

        mnit_qldanhmuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/danhmuc.png"))); // NOI18N
        mnit_qldanhmuc.setText("Quản lý danh mục");
        mnit_qldanhmuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnit_qldanhmucActionPerformed(evt);
            }
        });
        jMenu1.add(mnit_qldanhmuc);
        jMenu1.add(jSeparator1);

        mnit_qlmonan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/quanlymonan.png"))); // NOI18N
        mnit_qlmonan.setText("Quản lý món ăn");
        mnit_qlmonan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnit_qlmonanActionPerformed(evt);
            }
        });
        jMenu1.add(mnit_qlmonan);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hóa đơn");

        mnit_taohoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/taohoadon.png"))); // NOI18N
        mnit_taohoadon.setText("Tạo hóa đơn");
        mnit_taohoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnit_taohoadonActionPerformed(evt);
            }
        });
        jMenu2.add(mnit_taohoadon);
        jMenu2.add(jSeparator2);

        mnit_qlhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/quanlyhoadon.png"))); // NOI18N
        mnit_qlhoadon.setText("Quản lý hóa đơn");
        mnit_qlhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnit_qlhoadonActionPerformed(evt);
            }
        });
        jMenu2.add(mnit_qlhoadon);
        jMenu2.add(jSeparator3);

        mnit_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/thongke.png"))); // NOI18N
        mnit_thongke.setText("Thống kê");
        mnit_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnit_thongkeActionPerformed(evt);
            }
        });
        jMenu2.add(mnit_thongke);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Người dùng");

        mnit_qlkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nguoidung.png"))); // NOI18N
        mnit_qlkhachhang.setText("Quản lý khách hàng");
        mnit_qlkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnit_qlkhachhangActionPerformed(evt);
            }
        });
        jMenu3.add(mnit_qlkhachhang);
        jMenu3.add(jSeparator4);

        mnit_qlnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nhanvien.png"))); // NOI18N
        mnit_qlnhanvien.setText("Quản lý nhân viên");
        mnit_qlnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnit_qlnhanvienActionPerformed(evt);
            }
        });
        jMenu3.add(mnit_qlnhanvien);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tài khoản");

        mnit_doimatkhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/doimatkhau.png"))); // NOI18N
        mnit_doimatkhau.setText("Đổi mật khẩu");
        mnit_doimatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnit_doimatkhauActionPerformed(evt);
            }
        });
        jMenu4.add(mnit_doimatkhau);
        jMenu4.add(jSeparator5);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logout.png"))); // NOI18N
        jMenuItem9.setText("Đăng xuất");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnit_qlhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnit_qlhoadonActionPerformed
        // TODO add your handling code here:
        if (qlhoadon == null) {
            qlhoadon = new QLHoaDon();
            jTabbedPane1.add("Quản lý hóa đơn", qlhoadon);
            jTabbedPane1.setSelectedComponent(qlhoadon);
        }
    }//GEN-LAST:event_mnit_qlhoadonActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mnit_qldanhmucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnit_qldanhmucActionPerformed
        // TODO add your handling code here:
        if (qldanhmuc == null) {
            qldanhmuc = new QLDanhMuc();
            jTabbedPane1.add("Quản lý danh mục", qldanhmuc);
            jTabbedPane1.setSelectedComponent(qldanhmuc);
            if (user.getRole().equals("user")) {
                qldanhmuc.disnableBtn();
            }
        }
    }//GEN-LAST:event_mnit_qldanhmucActionPerformed

    private void mnit_qlmonanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnit_qlmonanActionPerformed
        // TODO add your handling code here:
        if (qlmonan == null) {
            qlmonan = new QLMonAn();
            jTabbedPane1.add("Quản lý món ăn", qlmonan);
            jTabbedPane1.setSelectedComponent(qlmonan);
            if (user.getRole().equals("user")) {
                qlmonan.setDisable();
            }
        }
    }//GEN-LAST:event_mnit_qlmonanActionPerformed

    private void mnit_taohoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnit_taohoadonActionPerformed
        // TODO add your handling code here:
        if (qlbanhang == null) {
            qlbanhang = new QLBanHang();
            jTabbedPane1.add("Quản lý bán hàng", qlbanhang);
            jTabbedPane1.setSelectedComponent(qlbanhang);
        }

    }//GEN-LAST:event_mnit_taohoadonActionPerformed

    private void mnit_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnit_thongkeActionPerformed
        // TODO add your handling code here:
        if (thongke == null) {
            thongke = new ThongKe();
            jTabbedPane1.add("Thống kê", thongke);
            jTabbedPane1.setSelectedComponent(thongke);
        }

    }//GEN-LAST:event_mnit_thongkeActionPerformed

    private void mnit_qlkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnit_qlkhachhangActionPerformed
        // TODO add your handling code here:
        if (qlkhachhang == null) {
            qlkhachhang = new QLKhachHang();
            jTabbedPane1.add("Quản lý khách hàng", qlkhachhang);
            jTabbedPane1.setSelectedComponent(qlkhachhang);
        }

    }//GEN-LAST:event_mnit_qlkhachhangActionPerformed

    private void mnit_qlnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnit_qlnhanvienActionPerformed
        // TODO add your handling code here:
        if (qlnhanvien == null) {
            qlnhanvien = new QLNhanVien();
            jTabbedPane1.add("Quản lý nhân viên", qlnhanvien);
            jTabbedPane1.setSelectedComponent(qlnhanvien);
        }

    }//GEN-LAST:event_mnit_qlnhanvienActionPerformed

    private void mnit_doimatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnit_doimatkhauActionPerformed
        // TODO add your handling code here:
        if (doimatkhau == null) {
            doimatkhau = new DoiMatKhau(user);
            System.out.println("thành công");
        }
    }//GEN-LAST:event_mnit_doimatkhauActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        updateMain();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main(new User("admin", "admin", "admin")).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mnit_doimatkhau;
    private javax.swing.JMenuItem mnit_qldanhmuc;
    private javax.swing.JMenuItem mnit_qlhoadon;
    private javax.swing.JMenuItem mnit_qlkhachhang;
    private javax.swing.JMenuItem mnit_qlmonan;
    private javax.swing.JMenuItem mnit_qlnhanvien;
    private javax.swing.JMenuItem mnit_taohoadon;
    private javax.swing.JMenuItem mnit_thongke;
    // End of variables declaration//GEN-END:variables
}
