/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DAO.CategoryDAO;
import DAO.ProductDAO;
import Dialog.ShowDialog;
import Models.Category;
import Models.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sangtm
 */
public class QLDanhMuc extends javax.swing.JPanel {

    ArrayList<Category> listCa = new ArrayList<>();
    ArrayList<Product> listP = new ArrayList<>();

    /**
     * Creates new form QLDanhMuc
     */
    public QLDanhMuc() {
        initComponents();
        loadList();
        fillTable();
        selectFirstRow();
    }

    public void selectFirstRow() {
        if (tb_fill.getRowCount() > 0) {
            tb_fill.setRowSelectionInterval(0, 0);
            fillForm();
        }
    }

    public void disnableBtn() {
        btn_them.setEnabled(false);
        btn_sua.setEnabled(false);
        btn_xoa.setEnabled(false);

    }

    public void loadList() {
        listCa = CategoryDAO.getList();
        listP = ProductDAO.getList();
    }

    public void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) tb_fill.getModel();
        dtm.setRowCount(0);
        for (Category l : listCa) {
            dtm.addRow(new Object[]{l.getId(), l.getTendanhmuc()});
        }
    }

    public void fillForm() {
        int i = tb_fill.getSelectedRow();
        tf_madanhmuc.setText(String.valueOf(listCa.get(i).getId()));
        tf_tendanhmuc.setText(listCa.get(i).getTendanhmuc());
    }

    public void deleteProduct(int id_cate) {
        for (Product l : listP) {
            if (id_cate == l.getId_category()) {
                ProductDAO.deleteProduct(l.getId());
            }
        }
    }

    public void clearForm() {
        tf_madanhmuc.setText("");
        tf_tendanhmuc.setText("");
    }

    public boolean checkTenDanhMuc(String ten) {
        DefaultTableModel dtm = (DefaultTableModel) tb_fill.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            if (ten.equalsIgnoreCase((String) dtm.getValueAt(i, 1))) {
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_madanhmuc = new javax.swing.JTextField();
        tf_tendanhmuc = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_fill = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã danh mục:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên danh mục:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        tf_madanhmuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_madanhmuc.setEnabled(false);
        tf_madanhmuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_madanhmucActionPerformed(evt);
            }
        });
        jPanel1.add(tf_madanhmuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 122, -1));

        tf_tendanhmuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tf_tendanhmuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 122, -1));

        btn_them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel1.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        btn_sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 97, -1));

        btn_xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/xoaDanhMuc.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 97, -1));

        tb_fill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_fill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã danh mục", "Tên danh mục"
            }
        ));
        tb_fill.setRowHeight(25);
        tb_fill.setRowMargin(2);
        tb_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_fillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_fill);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 583, 332));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("QUẢN LÝ DANH MỤC");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_madanhmucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_madanhmucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_madanhmucActionPerformed

    private void tb_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_fillMouseClicked
        // TODO add your handling code here:
        fillForm();
    }//GEN-LAST:event_tb_fillMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String tendanhmuc = tf_tendanhmuc.getText().trim();
        if (tendanhmuc.isEmpty()) {
            ShowDialog.openMessage(this, "Tên danh mục không hợp lệ!", "Thông báo");
            return;
        }
        if (checkTenDanhMuc(tendanhmuc)) {
            ShowDialog.openMessage(this, "Danh mục đã tồn tại!", "Thông báo");
            return;
        }
        CategoryDAO.insertCategory(tf_tendanhmuc.getText());
        loadList();
        fillTable();
        clearForm();
        ShowDialog.openMessage(this, "Thêm danh mục thành công!", "Thông báo");
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        if (tf_madanhmuc.getText().isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng chọn danh mục!", "Thông báo");
            return;
        }
        int id = Integer.parseInt(tf_madanhmuc.getText());
        String tendanhmuc = tf_tendanhmuc.getText().trim();
        if (tendanhmuc.isEmpty()) {
            ShowDialog.openMessage(this, "Tên danh mục không hợp lệ!", "Thông báo");
            return;
        }
        if (checkTenDanhMuc(tendanhmuc)) {
            ShowDialog.openMessage(this, "Danh mục đã tồn tại!", "Thông báo");
            return;
        }
        CategoryDAO.updateCategory(id, tendanhmuc, "Đang hoạt động");
        loadList();
        fillTable();
        clearForm();
        ShowDialog.openMessage(this, "Sửa thành công!", "Thông báo");

    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        loadList();
        if (tf_madanhmuc.getText().isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng chọn danh mục!", "Thông báo");
            return;
        }
        int i = ShowDialog.showConfirm(this, "Bạn có muốn xóa danh mục đã chọn?", "Xác nhận");
        if (i == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tf_madanhmuc.getText());
            CategoryDAO.deleteCategory(id, "Không hoạt động");
            deleteProduct(id);
            loadList();
            fillTable();
            clearForm();
            ShowDialog.openMessage(this, "Xóa thành công!", "Thông báo");
        } else {
            ShowDialog.openMessage(this, "Hủy xóa!", "Thông báo");

        }
    }//GEN-LAST:event_btn_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_fill;
    private javax.swing.JTextField tf_madanhmuc;
    private javax.swing.JTextField tf_tendanhmuc;
    // End of variables declaration//GEN-END:variables
}
