/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DAO.CustomerDAO;
import Dialog.ShowDialog;
import Models.Customer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sangtm
 */
public class QLKhachHang extends javax.swing.JPanel {

    ArrayList<Customer> listC = new ArrayList<>();

    /**
     * Creates new form QLKhachHang
     */
    public QLKhachHang() {
        initComponents();
        loadList();
        fillTable();
    }

    public void loadList() {
        listC = CustomerDAO.getList();
    }

    public void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) tb_fill.getModel();
        dtm.setRowCount(0);
        for (Customer l : listC) {
            String gioitinh = l.getGioitinh() == 1 ? "Nam" : "Nữ";
            dtm.addRow(new Object[]{l.getId(), l.getHoten(), l.getSdt(), gioitinh, l.getDiachi()});
        }
    }

    //hiển thị thông tin khách hàng lên form khi chọn trong bảng
    public void fillForm() {
        int index = tb_fill.getSelectedRow();
        tf_ma.setText(String.valueOf(listC.get(index).getId()));
        tf_ten.setText(listC.get(index).getHoten());
        tf_sdt.setText(listC.get(index).getSdt());
        if (listC.get(index).getGioitinh() == 1) {
            rbtn_nam.setSelected(true);
        } else {
            rbtn_nu.setSelected(true);
        }
        ta_diachi.setText(listC.get(index).getDiachi());
    }

    //làm mới form
    public void clearForm() {
        tf_ma.setText("");
        tf_ten.setText("");
        tf_sdt.setText("");
        rbtn_nam.setSelected(true);
        ta_diachi.setText("");
        tf_sodienthoai.setText("");
    }
    
    public int timKhachHang(String sdt) {
        for (Customer l : listC) {
            if (l.getSdt().equals(sdt)) {
                return listC.indexOf(l);
            }
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtn_gioitinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_ma = new javax.swing.JTextField();
        tf_ten = new javax.swing.JTextField();
        tf_sdt = new javax.swing.JTextField();
        rbtn_nam = new javax.swing.JRadioButton();
        rbtn_nu = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_diachi = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_fill = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btn_timkiem = new javax.swing.JButton();
        tf_sodienthoai = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 22, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã khách hàng:");

        tf_ma.setEditable(false);
        tf_ma.setBackground(new java.awt.Color(255, 255, 255));
        tf_ma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_ma.setEnabled(false);

        tf_ten.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tf_sdt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        rbtn_nam.setBackground(new java.awt.Color(255, 255, 255));
        gbtn_gioitinh.add(rbtn_nam);
        rbtn_nam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_nam.setSelected(true);
        rbtn_nam.setText("Nam");

        rbtn_nu.setBackground(new java.awt.Color(255, 255, 255));
        gbtn_gioitinh.add(rbtn_nu);
        rbtn_nu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_nu.setText("Nữ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số điện thoại:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giới tính:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Địa chỉ:");

        ta_diachi.setColumns(20);
        ta_diachi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ta_diachi.setRows(5);
        jScrollPane2.setViewportView(ta_diachi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtn_nam)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_nu)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tf_sdt)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_ma)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(82, 82, 82)
                        .addComponent(tf_ten)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_nam)
                    .addComponent(rbtn_nu)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 81, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 83, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        btn_them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/addNVKH.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel4.add(btn_them);

        btn_xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete.png"))); // NOI18N
        btn_xoa.setText("  Xóa   ");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_xoa);

        btn_sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editKHNV.png"))); // NOI18N
        btn_sua.setText(" Sửa  ");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_sua);

        btn_lammoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lammoi.png"))); // NOI18N
        btn_lammoi.setText("Làm mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        jPanel4.add(btn_lammoi);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 179, 245, 119));

        tb_fill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Số điện thoại", "Giới tính", "Địa chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_fill.setRowHeight(25);
        tb_fill.setRowMargin(2);
        tb_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_fillMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_fill);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 362, 880, 303));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/login.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 54, -1, -1));

        btn_timkiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 304, -1, -1));

        tf_sodienthoai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tf_sodienthoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 307, 144, -1));

        jLabel9.setBackground(new java.awt.Color(0, 153, 153));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Bảng quản lý khách hàng:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 341, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_fillMouseClicked
        // TODO add your handling code here:
        fillForm();
    }//GEN-LAST:event_tb_fillMouseClicked

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String hoten = tf_ten.getText().trim();
        String sdt = tf_sdt.getText().trim();
        String diachi = ta_diachi.getText().trim();
        int gioitinh = rbtn_nam.isSelected() ? 1 : 0;
        if (hoten.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập họ tên khách hàng!", "Thông báo");
            return;
        }
        if (sdt.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập số điện thoại khách hàng!", "Thông báo");
            return;
        }
        if (diachi.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập địa chỉ khách hàng!", "Thông báo");
            return;
        }
        CustomerDAO.insertCustomer(hoten, sdt, gioitinh, diachi);
        loadList();
        fillTable();
        clearForm();
        ShowDialog.openMessage(this, "Thêm thành công!", "Thông báo");

    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        String hoten = tf_ten.getText().trim();
        String sdt = tf_sdt.getText().trim();
        String diachi = ta_diachi.getText().trim();
        if (tf_ma.getText().isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng chọn khách hàng!", "Thông báo");
            return;
        }
        int id = Integer.parseInt(tf_ma.getText());
        int gioitinh = rbtn_nam.isSelected() ? 1 : 0;
        if (hoten.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập họ tên khách hàng!", "Thông báo");
            return;
        }
        if (sdt.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập số điện thoại khách hàng!", "Thông báo");
            return;
        }
        if (diachi.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập địa chỉ khách hàng!", "Thông báo");
            return;
        }
        CustomerDAO.updateCustomer(hoten, sdt, gioitinh, diachi, "Đang hoạt động", id);
        loadList();
        fillTable();
        clearForm();
        ShowDialog.openMessage(this, "Sửa thành công!", "Thông báo");

    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        String hoten = tf_ten.getText().trim();
        String sdt = tf_sdt.getText().trim();
        String diachi = ta_diachi.getText().trim();
        if (tf_ma.getText().isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng chọn khách hàng!", "Thông báo");
            return;
        }
        int id = Integer.parseInt(tf_ma.getText());
        int gioitinh = rbtn_nam.isSelected() ? 1 : 0;
        int i = ShowDialog.showConfirm(this, "Bạn có muốn xóa khách hàng?", "Xác nhận");
        if (i == JOptionPane.YES_OPTION) {
            CustomerDAO.updateCustomer(hoten, sdt, gioitinh, diachi, "Không hoạt động", id);
            clearForm();
            loadList();
            fillTable();
            clearForm();
            ShowDialog.openMessage(this, "Xóa thành công!", "Thông báo");
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String sdt = tf_sodienthoai.getText().trim();
        if (sdt.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập số điện thoại khách hàng cần tìm!", "Thông báo");
            return;
        }
        int indexRow = timKhachHang(sdt);
        if (indexRow == -1) {
            ShowDialog.openMessage(this, "Không tìm thấy khách hàng!", "Thông báo");
            return;
        } else {
            tb_fill.setRowSelectionInterval(indexRow, indexRow);
            fillForm();
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup gbtn_gioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbtn_nam;
    private javax.swing.JRadioButton rbtn_nu;
    private javax.swing.JTextArea ta_diachi;
    private javax.swing.JTable tb_fill;
    private javax.swing.JTextField tf_ma;
    private javax.swing.JTextField tf_sdt;
    private javax.swing.JTextField tf_sodienthoai;
    private javax.swing.JTextField tf_ten;
    // End of variables declaration//GEN-END:variables
}
