/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DAO.StaffDAO;
import DAO.UserDAO;
import Dialog.ShowDialog;
import Models.Staff;
import Models.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanhVinh
 */
public class QLNhanVien extends javax.swing.JPanel {

    ArrayList<Staff> listS = new ArrayList<>();
    ArrayList<User> listU = new ArrayList<>();

    /**
     * Creates new form QuanLyNhanVien
     */
    public QLNhanVien() {
        initComponents();
        loadList();
        fillTable();
    }

    public void loadList() {
        listS = StaffDAO.getList();
        listU = UserDAO.getList();
    }

    public void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) tb_fill.getModel();
        dtm.setRowCount(0);
        for (Staff l : listS) {
            String gioitinh = l.getGioitinh() == 1 ? "Nam" : "Nữ";
            dtm.addRow(new Object[]{l.getId(), l.getHoten(), l.getSdt(), gioitinh, l.getDiachi(), l.getTaikhoan(), l.getMatkhau()});
        }
    }

    public int checkUsername(String username) {
        for (User l : listU) {
            if (l.getUsername().equalsIgnoreCase(username)) {
                return 1;
            }
        }
        return 0;
    }

    public void clearForm() {
        tf_ma.setText("");
        tf_hoten.setText("");
        tf_sdt.setText("");
        tf_matkhau.setText("");
        tf_taikhoan.setText("");
        rbtn_nam.setSelected(true);
        ta_diachi.setText("");
    }

    public void fillForm() {
        int i = tb_fill.getSelectedRow();
        tf_ma.setText(String.valueOf(listS.get(i).getId()));
        tf_hoten.setText(listS.get(i).getHoten());
        tf_sdt.setText(listS.get(i).getSdt());
        if (listS.get(i).getGioitinh() == 1) {
            rbtn_nam.setSelected(true);
        } else {
            rbtn_nu.setSelected(true);
        }
        ta_diachi.setText(listS.get(i).getDiachi());
        tf_taikhoan.setText(listS.get(i).getTaikhoan());
        tf_matkhau.setText(listS.get(i).getMatkhau());
    }

    public String searchUsername(int id) {
        for (Staff l : listS) {
            if (l.getId() == id) {
                return l.getTaikhoan();
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblQuanLyNhanVien = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        tf_ma = new javax.swing.JTextField();
        tf_hoten = new javax.swing.JTextField();
        tf_sdt = new javax.swing.JTextField();
        rbtn_nam = new javax.swing.JRadioButton();
        rbtn_nu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_diachi = new javax.swing.JTextArea();
        tf_taikhoan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_fill = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tf_matkhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_lammoi = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 153, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblQuanLyNhanVien.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQuanLyNhanVien.setForeground(new java.awt.Color(255, 153, 0));
        lblQuanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");

        lblMa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMa.setText("Mã nhân viên:");

        lblHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHoTen.setText("Họ tên:");

        lblSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSDT.setText("Số điện thoại:");

        lblGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGioiTinh.setText("Giới tính:");

        lblDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDiaChi.setText("Địa chỉ:");

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTaiKhoan.setText("Tài khoản:");

        lblMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMatKhau.setText("Mật khẩu:");

        tf_ma.setEditable(false);
        tf_ma.setBackground(new java.awt.Color(255, 255, 255));
        tf_ma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_ma.setEnabled(false);

        tf_hoten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tf_sdt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sdtActionPerformed(evt);
            }
        });

        rbtn_nam.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGioiTinh.add(rbtn_nam);
        rbtn_nam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_nam.setSelected(true);
        rbtn_nam.setText("Nam");

        rbtn_nu.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupGioiTinh.add(rbtn_nu);
        rbtn_nu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtn_nu.setText("Nữ");

        ta_diachi.setColumns(20);
        ta_diachi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ta_diachi.setLineWrap(true);
        ta_diachi.setRows(5);
        jScrollPane1.setViewportView(ta_diachi);

        tf_taikhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_taikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_taikhoanActionPerformed(evt);
            }
        });

        tb_fill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ tên", "Số điện thoại", "Giới tính ", "Địa chỉ", "Tài khoản", "Mật khẩu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_fill.setRowHeight(25);
        tb_fill.setRowMargin(2);
        tb_fill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_fillMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_fill);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/login.png"))); // NOI18N

        tf_matkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Bảng quản lý nhân viên:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        btn_lammoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lammoi.png"))); // NOI18N
        btn_lammoi.setText("Làm mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        jPanel2.add(btn_lammoi);

        btn_them.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/addNVKH.png"))); // NOI18N
        btn_them.setText("Thêm   ");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel2.add(btn_them);

        btn_sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/editKHNV.png"))); // NOI18N
        btn_sua.setText(" Sửa    ");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sua);

        btn_xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete.png"))); // NOI18N
        btn_xoa.setText(" Xóa    ");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_xoa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 326, Short.MAX_VALUE)
                .addComponent(lblQuanLyNhanVien)
                .addGap(319, 319, 319))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMa)
                            .addComponent(lblHoTen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblSDT)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTaiKhoan)
                            .addComponent(lblMatKhau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_taikhoan)
                            .addComponent(tf_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGioiTinh)
                            .addComponent(lblDiaChi))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(rbtn_nam)
                                .addGap(29, 29, 29)
                                .addComponent(rbtn_nu))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(764, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, tf_hoten, tf_ma, tf_matkhau, tf_sdt, tf_taikhoan});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblQuanLyNhanVien)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMa)
                            .addComponent(tf_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoTen)
                            .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT)
                            .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_nam)
                            .addComponent(rbtn_nu)
                            .addComponent(lblGioiTinh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTaiKhoan)
                            .addComponent(tf_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatKhau)
                            .addComponent(tf_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tf_hoten, tf_ma, tf_matkhau, tf_sdt, tf_taikhoan});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sdtActionPerformed

    private void tf_taikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_taikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_taikhoanActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void tb_fillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_fillMouseClicked
        // TODO add your handling code here:
        fillForm();
    }//GEN-LAST:event_tb_fillMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String hoten = tf_hoten.getText().trim();
        if (hoten.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập họ tên nhân viên!", "Thông báo");
            return;
        }
        String sdt = tf_sdt.getText().trim();
        if (sdt.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập số điện thoại nhân viên!", "Thông báo");
            return;
        }
        int gioitinh = rbtn_nam.isSelected() ? 1 : 0;
        String diachi = ta_diachi.getText().trim();
        if (diachi.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập địa chỉ nhân viên!", "Thông báo");
            return;
        }
        String taikhoan = tf_taikhoan.getText().trim();
        if (taikhoan.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập tài khoản nhân viên!", "Thông báo");
            return;
        }
        if (checkUsername(taikhoan) == 1) {
            ShowDialog.openMessage(this, "Tài khoản đã tồn tại!", "Thông báo");
            return;
        }
        String matkhau = tf_matkhau.getText().trim();
        if (matkhau.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập mật khẩu nhân viên!", "Thông báo");
            return;
        }
        StaffDAO.insertStaff(hoten, sdt, gioitinh, diachi, taikhoan, matkhau);
        loadList();
        fillTable();
        ShowDialog.openMessage(this, "Thêm thành công!", "Thông báo");
        clearForm();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        if (tf_ma.getText().isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng chọn nhân viên cần xóa!", "Thông báo");
            return;
        }
        int id = Integer.parseInt(tf_ma.getText());
        StaffDAO.deleteStaff(id);
        String username = searchUsername(id);
        int i = ShowDialog.showConfirm(this, "Bạn có muốn xóa nhân viên?", "Xác nhận");
        if (i == JOptionPane.YES_OPTION) {
            if (username != null) {
                UserDAO.deleteUser(username);
            }
            loadList();
            fillTable();
            clearForm();
            ShowDialog.openMessage(this, "Xóa thành công!", "Thông báo");
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        if (tf_ma.getText().isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng chọn nhân viên cần sửa!", "Thông báo");
            return;
        }
        int id = Integer.parseInt(tf_ma.getText());
        String hoten = tf_hoten.getText().trim();
        if (hoten.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập họ tên nhân viên!", "Thông báo");
            return;
        }
        String sdt = tf_sdt.getText().trim();
        if (sdt.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập số điện thoại nhân viên!", "Thông báo");
            return;
        }
        int gioitinh = rbtn_nam.isSelected() ? 1 : 0;
        String diachi = ta_diachi.getText().trim();
        if (diachi.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập địa chỉ nhân viên!", "Thông báo");
            return;
        }
        String matkhau = tf_matkhau.getText().trim();
        if (matkhau.isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập mật khẩu nhân viên!", "Thông báo");
            return;
        }
        StaffDAO.updateStaff(id, hoten, sdt, gioitinh, diachi, matkhau);
        loadList();
        fillTable();
        clearForm();
        ShowDialog.openMessage(this, "Sửa thành công!", "Thông báo");

    }//GEN-LAST:event_btn_suaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGioiTinh;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblQuanLyNhanVien;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JRadioButton rbtn_nam;
    private javax.swing.JRadioButton rbtn_nu;
    private javax.swing.JTextArea ta_diachi;
    private javax.swing.JTable tb_fill;
    private javax.swing.JTextField tf_hoten;
    private javax.swing.JTextField tf_ma;
    private javax.swing.JTextField tf_matkhau;
    private javax.swing.JTextField tf_sdt;
    private javax.swing.JTextField tf_taikhoan;
    // End of variables declaration//GEN-END:variables
}
