/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Database.DatabaseHelper;
import Dialog.ShowDialog;
import Format.Formater;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sangtm
 */
public class ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        addItemCbb();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
        Date getTime = new Date();
        int time = Integer.parseInt(sdf.format(getTime));
        fillTableThang(time);
    }

    public void addItemCbb() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy");
        Date getTime = new Date();
        int time = Integer.parseInt(sdf.format(getTime));
        cbb_nam.addItem(String.valueOf(time));
        cbb_nam.addItem(String.valueOf(time - 1));
        cbb_nam.addItem(String.valueOf(time - 2));
    }

    public void fillTableThang(int nam) {
        DefaultTableModel dtm = (DefaultTableModel) tb_thang.getModel();
        dtm.setRowCount(0);
        try {
            Connection conn = DatabaseHelper.getConnection();
            String sql = "SELECT * FROM dbo.f_thongkethang(?)";
            CallableStatement cs = conn.prepareCall(sql);

            cs.setInt(1, nam);

            ResultSet rs = cs.executeQuery();

            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getInt(1), rs.getInt(2), rs.getInt(3)});
            }

            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void setDoanhThuThang() {
        DefaultTableModel dtm = (DefaultTableModel) tb_thang.getModel();
        int doanhthu = 0;
        for (int i = 0; i < 12; i++) {
            doanhthu += (int) dtm.getValueAt(i, 2);
        }
        lb_tongdoanhthuthang.setText(Formater.formatVND(doanhthu));
    }

    public void fillTableNam(int batdau, int ketthuc) {
        DefaultTableModel dtm = (DefaultTableModel) tb_nam.getModel();
        dtm.setRowCount(0);
        try {
            Connection conn = DatabaseHelper.getConnection();
            String sql = "SELECT * FROM dbo.f_thongkenam(?, ?)";
            CallableStatement cs = conn.prepareCall(sql);

            cs.setInt(1, batdau);
            cs.setInt(2, ketthuc);

            ResultSet rs = cs.executeQuery();

            while (rs.next()) {
                dtm.addRow(new Object[]{rs.getInt(1), rs.getInt(2), rs.getInt(3)});
            }

            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void setDoanhThuNam() {
        DefaultTableModel dtm = (DefaultTableModel) tb_nam.getModel();
        int doanhthu = 0;
        for (int i = 0; i < tb_nam.getRowCount(); i++) {
            doanhthu += (int) dtm.getValueAt(i, 2);
        }
        lb_doanhthunam.setText(Formater.formatVND(doanhthu));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_nam = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_batdau = new javax.swing.JTextField();
        tf_ketthuc = new javax.swing.JTextField();
        btn_thongke = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lb_doanhthunam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbb_nam = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_thang = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lb_tongdoanhthuthang = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Thống kê theo năm");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        tb_nam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_nam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Năm", "Số hóa đơn", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_nam.setRowHeight(25);
        tb_nam.setRowMargin(2);
        jScrollPane1.setViewportView(tb_nam);
        if (tb_nam.getColumnModel().getColumnCount() > 0) {
            tb_nam.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 144, 390, 341));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Năm bắt đầu:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 79, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Năm kết thúc:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 106, -1, -1));

        tf_batdau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tf_batdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 78, 100, -1));

        tf_ketthuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(tf_ketthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 105, 100, -1));

        btn_thongke.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/thongKeSearch.png"))); // NOI18N
        btn_thongke.setText("Thống kê");
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongkeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 87, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tống doanh thu:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 512, -1, -1));

        lb_doanhthunam.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lb_doanhthunam.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(lb_doanhthunam, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 512, 278, 17));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Thống kê theo tháng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Năm:");

        cbb_nam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbb_nam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_namItemStateChanged(evt);
            }
        });

        tb_thang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tb_thang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tháng", "Số hóa đơn", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_thang.setRowHeight(25);
        tb_thang.setRowMargin(2);
        jScrollPane3.setViewportView(tb_thang);
        if (tb_thang.getColumnModel().getColumnCount() > 0) {
            tb_thang.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tổng doanh thu:");

        lb_tongdoanhthuthang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lb_tongdoanhthuthang.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_tongdoanhthuthang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel5)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(cbb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_tongdoanhthuthang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongkeActionPerformed
        // TODO add your handling code here:
        if (tf_batdau.getText().trim().isEmpty() || tf_ketthuc.getText().trim().isEmpty()) {
            ShowDialog.openMessage(this, "Vui lòng nhập khoảng năm cần tìm!", "Thông báo");
            return;
        }
        int batdau;
        int ketthuc;
        try {
            batdau = Integer.parseInt(tf_batdau.getText().trim());
            ketthuc = Integer.parseInt(tf_ketthuc.getText().trim());
        } catch (Exception e) {
            System.out.println(e);
            ShowDialog.openMessage(this, "Vui lòng nhập đúng định dạng!", "Thông báo");
            return;
        }
        if (batdau > ketthuc || batdau < 2000 || (ketthuc > Integer.parseInt(cbb_nam.getItemAt(0)))) {
            ShowDialog.openMessage(this, "Không thống kê được!", "Thông báo");
            return;
        }
        fillTableNam(batdau, ketthuc);
        setDoanhThuNam();
    }//GEN-LAST:event_btn_thongkeActionPerformed

    private void cbb_namItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_namItemStateChanged
        // TODO add your handling code here:
        int strNam = cbb_nam.getSelectedIndex();
        int nam = Integer.parseInt(cbb_nam.getItemAt(strNam));
        fillTableThang(nam);
        setDoanhThuThang();
    }//GEN-LAST:event_cbb_namItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thongke;
    private javax.swing.JComboBox<String> cbb_nam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_doanhthunam;
    private javax.swing.JLabel lb_tongdoanhthuthang;
    private javax.swing.JTable tb_nam;
    private javax.swing.JTable tb_thang;
    private javax.swing.JTextField tf_batdau;
    private javax.swing.JTextField tf_ketthuc;
    // End of variables declaration//GEN-END:variables
}
